### ISSUE TITLE
Cataloguspagina's

### ISSUE THREAD

**Issue by freeaanzee** [OxfamFairTrade/ob2c#14]
- Paginabreedte en breadcrumbs gelijk zetten met ander pagina's (desnoods grid van 3 productkolommen nemen)
- Zoekbalk opmaken (eventueel ondersteuning voor instant search proberen toevoegen)
- Default product filters in zijbalk opmaken
  - categorieën: keuze is exclusief => radio buttons
  - voedingsvoorkeuren: keuze is supplementair => checkboxes
  - herkomstland: lange lijst => dropdown indien mogelijk weergeven als lookup field?
- Custom product filters boven product grid opmaken (dropdowns)
- Optionele banner (= volledige rij) en panel (= op de plek van een product) voorzien
- Afwijkende 'sfeervolle' templates per categorie (=> bv. koffieboontjes bij 'Koffie')

**Comment by freeaanzee** [comment]
Ik heb woocommerce/loop/add-to-cart.php voorzien van een #open-store-selector zodat alle winkelmandknoppen op het hoofdniveau (waar je niet echt kunt shoppen) ook de store selector oproepen. Dat lijkt echter niet te werken, wellicht omdat er nu meerdere elementen met die ID op één pagina staan? Switchen naar een klasse?

**Comment by mathysp** [comment]
Ik heb de styling/scripting van de filters in de sidebar aangepast. Zou voor mobiel & desktop nu in orde moeten zijn.

Echter moet die widget van de "Laatst bekeken" producten nog een andere plaats krijgen in de markup. Nu word die via php geprint in eenzelfde div. Zie sidebar.php lijn 51.

**Comment by freeaanzee** [comment]
> Ik heb woocommerce/loop/add-to-cart.php voorzien van een #open-store-selector zodat alle winkelmandknoppen op het hoofdniveau (waar je niet echt kunt shoppen) ook de store selector oproepen. Dat lijkt echter niet te werken, wellicht omdat er nu meerdere elementen met die ID op één pagina staan? Switchen naar een klasse?

Fixed met 4c1d892!
